<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'oirs' => [
        'key' => env('OIRS_APP_KEY'),
        'base_url' => env('OIRS_BASE_URL'),
        'terminal_base_url' => env('OIRS_TERMINAL_BASE_URL', env('OIRS_BASE_URL')),
        'hash_key' => env('OIRS_HASH_KEY'),
    ],

    'terminals' => [
        // Domain for logins generated by the bulk terminal import. These
        // addresses identify an account; nothing is ever delivered to them.
        'email_domain' => env('TERMINAL_EMAIL_DOMAIN', 'ecgpos.local'),

        // Seeded administrator. Leave the password unset to have one generated
        // and printed once by the seeder.
        'admin_email' => env('TERMINAL_ADMIN_EMAIL', 'admin@ecgpos.local'),
        'admin_name' => env('TERMINAL_ADMIN_NAME', 'ECG POS Administrator'),
        'admin_terminal_id' => env('TERMINAL_ADMIN_TERMINAL_ID', 'ADMIN-001'),
        'admin_password' => env('TERMINAL_ADMIN_PASSWORD'),
    ],

];
